    datatypes = {"NONE": 0,
                 "BYTE": 33,
                 "SHORT": 34,
                 "INT": 35,
                 "LONG": 36,
                 "FLOAT": 15,
                 "DOUBLE": 16,
                 "CHAR": 1,
                 "STRING": 46,
                 "COMMAND_CODE": 48,
                 "PARAMETER": 49,
                 "LIBRARY_ID": 50,
                 "MATRIX_ID": 51,
                 "MATRIX_INFO": 52,
                 "DISTMATRIX": 53}